---
abstract: 'Type constraints and coercions for Perl'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: '0'
  File::Temp: '0'
  IO::File: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  lib: '0'
  namespace::autoclean: '0'
  open: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Specio
requires:
  B: '0'
  Carp: '0'
  Class::Load: '0'
  Devel::PartialDump: '0'
  Devel::StackTrace: '0'
  Eval::Closure: '0'
  Exporter: '0'
  Lingua::EN::Inflect: '0'
  List::MoreUtils: '0'
  Module::Runtime: '0'
  Params::Util: '0'
  Role::Tiny: '0'
  Role::Tiny::With: '0'
  Scalar::Util: '0'
  Storable: '0'
  Try::Tiny: '0'
  overload: '0'
  parent: '0'
  perl: v5.10.0
  re: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Specio
  homepage: http://metacpan.org/release/Specio
  repository: git://git.urth.org/Specio.git
version: '0.09'
x_authority: cpan:DROLSKY
