---
abstract: 'Type constraints and coercions for Perl'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  IO::File: 0
  Test::Fatal: 0
  Test::More: 0.88
  encoding: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Specio
requires:
  B: 0
  Carp: 0
  Class::Load: 0
  Devel::PartialDump: 0
  Eval::Closure: 0
  Exporter: 0
  Lingua::EN::Inflect: 0
  List::AllUtils: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Clone: 0
  MooseX::Params::Validate: 0
  MooseX::SemiAffordanceAccessor: 0
  Params::Util: 0
  Scalar::Util: 0
  Sub::Name: 0
  Throwable::Error: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  overload: 0
  parent: 0
  perl: v5.10.0
  re: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Specio
  repository: git://git.urth.org/Specio.git
version: 0.06
