use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
drolsky
DROLSKY
DROLSKY's
PayPal
Rolsky
Rolsky's
API
boolification
ClassName
Coercions
coercions
de
distro
globification
inlinable
inline
isa
Kogman
LaxVersionStr
ModuleName
MUTC
namespace
NegativeInt
NegativeNum
NegativeOrZeroInt
NegativeOrZeroNum
NonEmptySimpleStr
NonEmptyStr
PackageName
PARAMETERIZABLE
parameterizable
parameterization
parameterized
PositiveInt
PositiveNum
PositiveOrZeroInt
PositiveOrZeroNum
reimplementation
SafeIdentifier
ScalarRef
sigils
SIGNES
SimpleStr
SingleDigit
SPECIO
Specio
StrictVersionStr
subtype
subtypes
Throwable
Yuval
Dave
autarch
Karen
Etheridge
ether
lib
Coercion
Constraint
AnyCan
AnyDoes
AnyIsa
Enum
Intersection
ObjectCan
ObjectDoes
ObjectIsa
Parameterizable
Parameterized
Role
CanType
DoesType
Interface
IsaType
Simple
Union
Declare
DeclaredAt
Exception
Exporter
Helpers
Library
Builtins
Numeric
Perl
String
OO
PartialDump
Registry
Inlinable
TypeChecks
