use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007000
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
drolsky
DROLSKY
DROLSKY's
PayPal
Rolsky
Rolsky's
API
ClassName
Coercions
MUTC
PARAMETERIZABLE
SPECIO
ScalarRef
Specio
Throwable
boolification
coercions
de
distro
globification
inlinable
inline
isa
namespace
parameterizable
parameterization
parameterized
reimplementation
sigils
subtype
subtypes
Dave
autarch
Karen
Etheridge
ether
lib
Coercion
Constraint
AnyCan
AnyDoes
AnyIsa
Enum
ObjectCan
ObjectDoes
ObjectIsa
Parameterizable
Parameterized
Role
CanType
DoesType
Interface
IsaType
Simple
Declare
DeclaredAt
Exception
Exporter
Helpers
Library
Builtins
OO
Registry
Inlinable
TypeChecks
