use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007003
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib ) );
__DATA__
API
AnyCan
AnyDoes
AnyIsa
Builtins
CanType
ClassName
Coercion
Coercions
Constraint
DROLSKY
DROLSKY's
Dave
Declare
DeclaredAt
DoesType
Enum
Etheridge
Exception
Exporter
Helpers
Inlinable
Interface
Intersection
IsaType
Karen
Kogman
LaxVersionStr
Library
MUTC
ModuleName
NegativeInt
NegativeNum
NegativeOrZeroInt
NegativeOrZeroNum
NonEmptySimpleStr
NonEmptyStr
Num
Numeric
OO
ObjectCan
ObjectDoes
ObjectIsa
PARAMETERIZABLE
PackageName
Parameterizable
Parameterized
PartialDump
PayPal
Perl
PositiveInt
PositiveNum
PositiveOrZeroInt
PositiveOrZeroNum
RegexpRef
Registry
Role
Rolsky
Rolsky's
SIGNES
SPECIO
SafeIdentifier
ScalarRef
Simple
SimpleStr
SingleDigit
Specio
Str
StrictVersionStr
String
Throwable
TypeChecks
Union
Yuval
autarch
boolification
coercions
de
distro
drolsky
ether
globification
inlinable
inline
isa
lib
namespace
numification
parameterizable
parameterization
parameterized
reimplementation
sigils
subtype
subtypes
